- src/App.css
- src/SetupRepository.js
Found IDrive e2: the cheapest cloud storage in the market with no fees for egress. We use kopia for backups so tested extensively with kopia and found it to be way faster than other s3 providers like Backblaze B2, Wasabi etc. It deserves a place in this amazing tool.
> Add new affordable S3 storage provider

- src/App.js
- src/AppContext.js
- src/RepoStatus.js
- The repository description (e.g. "My Repository") now appears at the top of every page, just below the top navigation bar
- The repository description is a hyperlink (unstyled) leading to the "Repository" tab
- The "Connected To Repository" heading is no longer a heading, and, instead, appears as green text with a checkmark
The client only loads the repository description when the user goes to the "Repository" tab, so this newly-added repository description header will not be visible until that has happened. One way this could be resolved is by loading the repository "status" (i.e. details) at the app level, when the app first loads (rather than only when the "Repository" tab is first visited).
The "Repository" tab:
A tab other than the "Repository" tab:
The "Repository" tab:
A tab …
> Display repository description on every page

- src/SetupRepository.js
- Added vertical space between the "Repository Password" help text and the "Show/Hide Advanced Options" button
- Added vertical space between the "Show/Hide Advanced Options" button and the form it reveals/conceals
- Replaced a `&nbsp;` character being used for layout, with `margin` (so code is more "semantically accurate")
- Added vertical space between the form and the "Additional parameters..." footnote
- Added a period (`.`) to the end of a sentence
Note: The window was slightly larger for this screenshot, so the page elements appear slightly smaller than above.
> Refine appearance of "Create New Repository" form

- src/BeginRestore.js
This commit adds a new radial button (required value) to the snapshot
restore window allowing users to enable the sparse restore option.
When enabled, the restored snapshot's files are written sparsely,
minimizing disk allocations for the written content. This option is
disabled by default.
> Button to write restored snapshot files sparsely

- src/TasksTable.js
- src/tests/uiutil.test.js
- src/uiutil.js
- The durations in the "Status" column of the table on the "Tasks" page now appear as humanized strings (e.g. "a few seconds") instead of as a number of seconds (e.g. "2.7s"). The original "seconds" string is still accessible by hovering the mouse cursor over the humanized string.
- I widened the "Status" column of the same table so its contents fit on a single line. I also narrowed the "Start Time" column by the same amount (its contents still fit on a single line), so the total table width has not changed.
Fixes: https://github.com/kopia/kopia/issues/2055
> Display task status durations using larger time units

- src/BeginRestore.js
This commit updates the UI button to specify "sparse restores"
to use the same field name that is now expected by the Kopia
API server (from "sparse" to "writeSparseFiles").
> Update sparse restore field name

- src/contexts/UIPreferencesContext.tsx
This was caused by using `fetch()` instead of `axios`.
> fixed missing CSRF token when loading/saving preferences

- src/TaskLogs.js
Fixes kopia/kopia#2143
Switched to simple `<code>` instead of custom style:
Light mode:
Dark mode:
> fixed log detail color in dark mode

- public/index.html
Just removing the extra space
Related: https://github.com/kopia/kopia/pull/2140
> "Kopia UI" to "KopiaUI"

- package-lock.json
- package.json
- src/setupProxy.js
This PR uses `http-proxy-middleware` to workaround an error with the `proxy` config in `package.json` when using node 18.
Got the workaround from https://stackoverflow.com/a/70413065
> Fix npm start not working with node 18

- src/SetupRepository.jsx
The back button wasn`t behaving correctly when setting up a repository. The user could not navigate back once the path or url was given. 
The PR adds "providerSettings: {}" to the setState method.
I've attached to examples - one before and one after the fix. However, I am not very good at react js. Feedback is welcomed. 
https://user-images.githubusercontent.com/37236531/227763069-b7e92308-c82d-4685-8b8c-f755801eace4.mp4
https://user-images.githubusercontent.com/37236531/227763083-0dd7d8e5-4520-4090-8c4b-a205e1a9a1e7.mp4
Cheers,
> fix: back-button within SetupRepository

- src/TaskDetails.jsx
- src/tests/uiutil.test.js
- src/uiutil.jsx
Improve the format used to show task durations (and maybe also other durations):
- Avoid that the duration switches between a duration with and without fraction digit, e.g "1s" > "1.5s" > "2s". The UI gets very "nervous" -> always show a single fraction digit for duration < 10s
- always use the multi unit format, also for running tasks. When a task runs for several hours, I just don't want to see the number of seconds and convert this to hours myself
- use localization based number formatting to get e.g. `1,000 days`
- a wee simplification in `formatDuration()`
- changed `formatMagnitudesUsingMultipleUnits()`
- always show exact duration, not just the top two units. Especially while running, I want to see the exact duration.
- also don't include zero units, e.g. show `1 day` instead of `1 …
> Improve the format used to show task durations

- src/PolicyEditor/index.jsx
Fix the field name for the policy editor `script` field for before & after folder/snapshot actions.
Instead of using the `script` field, the `path` field was being used. This caused issues where using a script body value would fail becuase `path` expects only an executable file, not the contents of a sh/cmd script. Using the `script` field should properly allow an inline script to be used.
See API server reference for `ActionCommand`: https://github.com/kopia/kopia/blame/ba938cf58cc8db26eb373f6ddff5fc0e9c07af15/snapshot/policy/actions_policy.go#L23-L33
> Fix policy editor script field

- src/PolicyEditor/index.jsx
> fix: Policy editor for "Cache Miss" actually modifies/reads "cacheHit" property

- src/PolicyEditor/index.jsx
Hi, 
this PR may fix actions not being saved in the policy editor. Debuging the policy editor indicated that the method sanitizeActions(..) checks for "path" instead of script. The policy editor, however, stores the information in "script"
" {ActionRowScript(this, "actions.afterSnapshotRoot.script", "After Snapshot", "Script to run after snapshot")}"
Therefore, all actions are set to undefined and are never saved. The issue was introduced in https://github.com/kopia/htmlui/pull/133.
This PR may fix https://github.com/kopia/kopia/issues/3046
Feedback is welcomed. 
Cheers,
> fix(actions): actions are not saved after sanitizeActions()

- src/PolicyEditor/EffectiveListValue.jsx
- src/PolicyEditor/EffectiveTimesOfDayValue.jsx
- src/PolicyEditor/UpcomingSnapshotTimes.jsx
- src/PolicyEditor/index.jsx
https://github.com/kopia/htmlui/assets/249880/cde6b575-d077-4a0d-8f43-ff5cd2babde9
> support for cron-based schedules

- public/index.css
- public/index.html
- src/DirectoryObject.jsx
- src/css/App.css
- src/css/Theme.css
This PR comes with the following changes:
- Minor fixes for themes.
- Changed variant of navigation button in DirectoryObject.
- Removed index.css and reverted to old implementation
Feedback is welcomed.
Cheers
> fix(ui): Minor theme changes 

- src/SourcesTable.jsx
- src/contexts/UIPreferencesContext.tsx
When I connect to the server http page, I prefer to see all snapshots shown by default.  every time I switch away and come back I need to reselect 'All' instead of 'Local'.  This just makes the default a preference option
Requires https://github.com/kopia/kopia/pull/3289
> feat(ui): Allow specifying whether local or all snapshots are shown by default

- src/App.jsx
- src/SourcesTable.jsx
Hi, 
This PR is a fix of #186. Setting the state while rendering throws a JS error.
Setting the **selectedOwner** is now done after the component has been mounted. 
The rendering function then just interprets the selectedOwner. 
Feedback is welcomed. 
Cheers,
> fix(ui): Fixed error while rendering source table

- src/css/App.css
- src/css/Theme.css
Hi, 
this PR should fix the dark theme that is currently in production. 
Cheers,
> fix(ui): Fix for dark theme

- README.md
- dev-start-server.sh
A simple README might be better than no README :smiley:  
Could be improved later anyway.
And I added a simple script I use to start a kopia server for development, that also might help others.  
Not sure, if this needs to be excluded somewhere so that it's not bundled with the build?
> Added README.md and dev-start-server.sh script for development.

- src/PolicyEditor/index.jsx
This adds a UI configuration option for https://github.com/kopia/kopia/pull/3311
> feat(cli): Immediately create snapshot if time-of-day snapshot was missed

- src/PoliciesTable.jsx
- src/css/App.css
Hi, 
this PR fixes [#3343](https://github.com/kopia/kopia/issues/3343) that indicates that some policy badges are missing. These badges indicate an individual setting of policies. 
- Badges are now created in a loop, looping over all policy settings that have been changed
- Badges are now styled according to the primary color of the theme
This is how it should look:
Feedback is welcomed. 
Cheers,
> fix(ui): Fix missing badges in policy table

- src/css/App.css
Hi, 
this PR further fixes some color issues before moving to scss:
- Fixing the background color of the logs table
- Fixing the divider color of the breadcrumb navigation
This PR should fix https://github.com/kopia/kopia/issues/3379 and https://github.com/kopia/kopia/issues/3368
Feedback is welcomed.
> fix(ui): Fixing colors in dark theme

- src/css/App.css
Hi, 
this PR fixes the hint text visibility in dark mode. It was overridden by the latest refactoring. 
Feedback is welcomed. 
Cheers,
> fix(ui):  Fix hint text visibility in dark mode

- src/App.jsx
- src/css/App.css
This is a small cosmetic improvement to the navbar. It stops the active item from sliding everything left/right, by always reserving enough space for a bold font weight.
> Constant navbar width

- src/App.jsx
- src/pages/Snapshots.jsx
- src/utils/uiutil.jsx
Hi, 
this PR fixes https://github.com/kopia/kopia/issues/3489, https://github.com/kopia/kopia/issues/3490 and https://github.com/kopia/kopia/issues/3488.
- For #3489 the icon was wrapped inside a button
- For #3490, the word "start" was added to the tooltip. 
- For #3488, the nav-links were wrapped inside a span element. The nav-link class is set via the state
Feedback is welcomed.
> fix(ui): Changed button appearance and fixed tooltip

- src/contexts/UIPreferencesContext.tsx
Hi, 
this PR fixes situations, where the theme or font size can get out of sync with the html class list. 
- Theme and font size is now set in one function
- Class list elements are removed before they are set, preventing out of sync situations caused by ```replace``` elements
- Minor refactorings
Cheers,
> fix(ui): Fix out of sync situations while setting themes or font sizes

- src/components/SetupRepositoryFilesystem.jsx
- src/css/index.css
- src/forms/OptionalDirectory.jsx
- src/forms/OptionalField.jsx
- src/forms/RequiredDirectory.jsx
- src/pages/Policies.jsx
- src/pages/SnapshotCreate.jsx
- src/utils/uiutil.jsx
Hi, 
this PR comes with the following changes:
- Rewrote the directory selector and added a required and optional directory selector
- Added the directory selector to snapshot create and filesystem repository
- Fixed a bug, where the deletion of the snapshot path result in a nullpointer reference
This pr will fix https://github.com/kopia/kopia/issues/3453
Feedback is welcomed,
Cheers
> feat(ui): Added directory selector for snapshots and filesystem repository

- src/pages/Policies.jsx
- src/utils/uiutil.jsx
This PR addresses https://github.com/kopia/kopia/issues/4511
It relaxes the check for policy-creation to allow not just absolute paths, but also `user@host`, `@host` and `user@host:/absolute/path`
> feat(ui): allow creating per-host, per-user and foreign policies

- src/components/policy-editor/PolicyEditor.jsx
When checking files' extensions for compression, Kopia [compares the result of `filepath.Ext()`](https://github.com/kopia/kopia/blob/dbf5bacdc8f33f47047350164d43ac18335d595d/snapshot/policy/compression_policy.go#L59), which returns the last `.` in the filename and the text following it. This means the extensions to enable/disable compression should be in the form `.txt`, not `*.txt`.
This PR changes the placeholder on the text inputs for the UI for the relevant text fields to just be `.txt` and `.mp4` rather than `*.txt` and `*.mp4`.
> fix(kopiaui): Remove misleading asterisk from extension placeholders

- src/pages/SnapshotHistory.jsx
As reported by @dcog989 in https://github.com/kopia/kopia/pull/4565
This was broken by https://github.com/kopia/htmlui/pull/317
> fix(htmui): restored retention labels
